EventManagementSystem/Areas/Admin/Controllers/EventsManagerController.cs
using CloudinaryDotNet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using CloudinaryDotNet.Actions;
using EventManagementSystem.DataAccess.Repository;
using EventManagementSystem.Models;
using EventManagementSystem.Models.ViewModels;
using EventManagementSystem.Utilities;
using Microsoft.AspNetCore.Mvc.Filters;
using EventManagementSystem.DataAccess.Repository.Admin;
using NuGet.Versioning;
using EventManagementSystem.Services;

namespace EventManagementSystem.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class EventsManagerController : Controller
{
    private readonly IAdminEventRepository _adminEventRepository;
    private readonly IEventRepository _eventRepository;
    private readonly IAdminTicketTypeRepository _adminTicketTypeRepository;
    private readonly IEventService _eventService;
    private readonly UserManager<User> _userManager;
    private readonly Cloudinary _cloudinary;
    private const int MaximumTicketTypes = 10;

    public EventsManagerController(IAdminEventRepository adminEventRepository, IEventRepository eventRepository, UserManager<User> userManager, Cloudinary cloudinary, IWebHostEnvironment webHostEnvironment, IAdminTicketTypeRepository adminTicketTypeRepository, IEventService eventService)
    {
        _adminEventRepository = adminEventRepository;
        _eventRepository = eventRepository;
        _userManager = userManager;
        _cloudinary = cloudinary;
        _adminTicketTypeRepository = adminTicketTypeRepository;
        _eventService = eventService;
    }
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        TempData["Referer"] = context.HttpContext.Request.Headers.Referer.ToString();
    }

    private int maxItem = 20;
    public async Task<IActionResult> Index(string sortBy, int? pageNumber, string? searchQuery)
    {
        ViewData["CurrentSort"] = sortBy;
        ViewData["IdSortParam"] = string.IsNullOrEmpty(sortBy) || sortBy == "id_desc" ? "id" : "id_desc";
        ViewData["NameSortParam"] = sortBy == "name" ? "name_desc" : "name";
        ViewData["CategorySortParam"] = sortBy == "category" ? "category_desc" : "category";
        ViewData["CountrySortParam"] = sortBy == "country" ? "country_desc" : "country";
        ViewData["DateSortParam"] = sortBy == "date" ? "date_desc" : "date";
        ViewData["CurrentSearch"] = searchQuery;

        pageNumber ??= 1;

        var events = await _adminEventRepository
            .GetEventsSortedPagedAsync(sortBy, pageNumber, maxItem, searchQuery);

        int count;
        if (string.IsNullOrEmpty(searchQuery))
        {
            count = await _adminEventRepository.GetAllEventsCountAsync();
        }
        else
        {
            count = _adminEventRepository.GetAllEventsSearchCountAsync(searchQuery);
        }

        var exceptionDetail = HttpContext.Items["ExceptionDetails"] as string;
        if (!string.IsNullOrEmpty(exceptionDetail))
        {
            ViewBag.ExceptionDetails = exceptionDetail;
        }

        return View(new PaginatedList<Event>(events.ToList(), count, pageNumber.Value, maxItem));
    }

    public IActionResult Create()
    {
        var viewModel = new EventViewModel()
        {
            Event = new Event(),
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Create(EventViewModel eventViewModel)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user is not null)
            {
                var uploadResult = new ImageUploadResult();

                using (var stream = eventViewModel.ImagePath.OpenReadStream())
                {
                    uploadResult = await _cloudinary.UploadAsync(new ImageUploadParams()
                    {
                        File = new FileDescription(eventViewModel.ImagePath.FileName, stream),
                        PublicId = $"EventManager/{eventViewModel.Event.Category}/{Guid.NewGuid()}"
                    });
                }

                if (uploadResult is not null)
                {
                    var ticketTypes = eventViewModel.TicketTypes?
                        .Where(tt => !string.IsNullOrEmpty(tt.Name)).ToList();

                    if (ticketTypes?.Count == 0)
                    {
                        ticketTypes = [];
                        ticketTypes.Add(new TicketType()
                        {
                            Tickets = [],
                            Name = "Free",
                            Detail = $"Free Ticket on {eventViewModel.Event.Title}",
                            EventId = eventViewModel.Event.Id,
                            MaxCapital = int.MaxValue,
                            Price = 0
                        });
                    }

                    var newEvent = new Event()
                    {
                        Title = eventViewModel.Event.Title,
                        ShortDescription = eventViewModel.Event.ShortDescription,
                        Description = eventViewModel.Event.Description,
                        UserId = user.Id,
                        User = user,
                        Create_at = DateTime.Now,
                        StartDate = eventViewModel.Event.StartDate,
                        EndDate = eventViewModel.Event.EndDate,
                        VenueName = eventViewModel.Event.VenueName,
                        Latitude = eventViewModel.Event.Latitude,
                        Longitude = eventViewModel.Event.Longitude,
                        Country = eventViewModel.Event.Country,
                        Address = eventViewModel.Event.Address,
                        Image = uploadResult.Url.ToString(),
                        Transports = eventViewModel.Transports
                        .Where(t => t.Value == "true")
                        .Select(st => (Transport)Enum.Parse(typeof(Transport), st.Text)).ToList(),
                        Category = eventViewModel.Event.Category,
                        TicketTypes = ticketTypes
                    };

                    await _adminEventRepository.CreateAsync(newEvent);

                    TempData["Success"] = $"The event {newEvent.Title} was create successfully.";

                    _eventService.SetEvents();
                    return Redirect($"/event/details/{newEvent.Id}");
                }
            }
        }
        return View(eventViewModel);
    }

    public async Task<IActionResult> Edit(int? id)
    {
        if (id is not null && id != 0)
        {
            var eventToEdit = await _eventRepository.GetByIdAsync(id.Value);
            if (eventToEdit is not null)
            {
                var eventViewModel = new EventViewModel()
                {
                    Event = eventToEdit,
                };
                return View(eventViewModel);
            }
        }

        var backUrl = TempData["Referer"] as string;
        if (!string.IsNullOrEmpty(backUrl))
        {
            return Redirect(backUrl);
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EventViewModel eventViewModel)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user is not null)
            {
                if (eventViewModel.ImagePath is not null)
                {
                    using var stream = eventViewModel.ImagePath.OpenReadStream();
                    var uploadResult = await _cloudinary.UploadAsync(new ImageUploadParams()
                    {
                        File = new FileDescription(eventViewModel.ImagePath.FileName, stream),
                        PublicId = $"EventManager/{eventViewModel.Event.Category}/{Guid.NewGuid()}"
                    });

                    if (uploadResult is not null)
                    {
                        eventViewModel.Event.Image = uploadResult.Url.ToString();
                    }
                }

                var eventToEdit = eventViewModel.Event;

                eventViewModel.TicketTypes ??= [];
                var ticketTypes = eventViewModel.TicketTypes
                    .Where(tt => !string.IsNullOrEmpty(tt.Name)).ToList();

                if (ticketTypes?.Count == 0)
                {
                    ticketTypes = [];
                    ticketTypes.Add(new TicketType()
                    {
                        Tickets = [],
                        Name = "Free",
                        Detail = $"Free Ticket on {eventViewModel.Event.Title}",
                        EventId = eventViewModel.Event.Id,
                        MaxCapital = int.MaxValue,
                        Price = 0
                    });
                }

                eventToEdit.TicketTypes = ticketTypes;
                eventToEdit.Transports = eventViewModel.Transports
                    .Where(ts => ts.Value == "true")
                    .Select(ts => (Transport)Enum.Parse(typeof(Transport), ts.Text)).ToList();

                try
                {
                    await _adminEventRepository.EditAsync(eventToEdit);
                    _eventService.SetEvents();
                    return Redirect($"/event/details/{eventToEdit.Id}");
                }
                catch (Exception ex)
                {
                    TempData["Error"] = $"Edit event failed, {ex.Message}";
                }
            }
        }

        var backUrl = TempData["Referer"] as string;
        if (!string.IsNullOrEmpty(backUrl))
        {
            return Redirect(backUrl);
        }
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var eventToDelete = await _eventRepository.GetByIdAsync(id);

EventManagementSystem/Areas/Admin/Views/EventsManager/Create.cshtml
@model EventViewModel
<div class="container bg-dark py-5 px-5">
    <partial name="_AlertErrorSuccess" />
    <form class="px-md-5" asp-action="Create" method="post" enctype="multipart/form-data">
        @for (int i = 0; i < Model.TicketTypes.Count; i++)
        {
            <input asp-for="@Model.TicketTypes[i].Name" type="hidden" id="templateName_@i" />
            <input asp-for="@Model.TicketTypes[i].Detail" type="hidden" id="templateDetail_@i" />
            <input asp-for="@Model.TicketTypes[i].Price" type="hidden" id="templatePrice_@i" />
            <input asp-for="@Model.TicketTypes[i].MaxCapital" type="hidden" id="templateMaxCapital_@i" />
        }
        <div asp-validation-for="All" class="text-danger"></div>
        <fieldset class="px-lg-5">
            <legend class="text-center h1 fw-bold">CREATE EVENT</legend>
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <label asp-for="@Model.Event.Title" class="form-label mt-4">Title</label>
                        <input asp-for="@Model.Event.Title" type="text" class="form-control" placeholder="required*">
                        <span asp-validation-for="@Model.Event.Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div>
                        <label asp-for="@Model.Event.ShortDescription" class="form-label mt-4">Short Description</label>
                        <textarea asp-for="@Model.Event.ShortDescription" class="form-control" rows="1" placeholder="Maximum 50 words"></textarea>
                    </div>
                </div>
            </div>
            <div>
                <label asp-for="@Model.Event.Description" class="form-label mt-4">Full Description</label>
                <textarea asp-for="@Model.Event.Description" class="form-control" rows="3" placeholder="Maximum 1000 words"></textarea>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="@Model.Event.StartDate" class="form-label mt-4">Start Event Date</label>
                    <input asp-for="@Model.Event.StartDate" class="form-control" type="date" />
                </div>
                <div class="col-md-4">
                    <label asp-for="@Model.Event.EndDate" class="form-label mt-4">End Event Date</label>
                    <input asp-for="@Model.Event.EndDate" class="form-control" type="date" />
                </div>
                <div class="col-md-4">
                    <label asp-for="@Model.Event.VenueName" class="form-label mt-4">Venue Name</label>
                    <input asp-for="@Model.Event.VenueName" type="text" class="form-control" placeholder="Venue Name">
                </div>
            </div>

            <div class="row mt-4 d-flex justify-content-center">
                @*Map*@
                <div class="col-12" id="map" style="width: 1000px; height: 320px;"></div>
                <div class="col-md-6 mt-2">
                    <div class="input-group input-group-sm">
                        <span class="input-group-text">Latitude</span>
                        <input asp-for="@Model.Event.Latitude" id="latitude" type="text" class="form-control w-25 bg-secondary-subtle" aria-label="latitude input" readonly>
                    </div>
                </div>
                <div class="col-md-6 mt-2">
                    <div class="input-group input-group-sm">
                        <span class="input-group-text">Longitude</span>
                        <input asp-for="@Model.Event.Longitude" id="longitude" type="text" class="form-control w-25 bg-secondary-subtle" aria-label="longitude input" readonly>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="@Model.Event.Country" class="form-label mt-4">Country</label>
                    <input asp-for="@Model.Event.Country" id="countryName" type="text" class="form-control" placeholder="required">
                </div>
                <div class="col-md-8">
                    <label asp-for="@Model.Event.Address" class="form-label mt-4">Address</label>
                    <input asp-for="@Model.Event.Address" id="addressName" type="text" class="form-control" placeholder="required">
                </div>
            </div>
            <div>
                <label asp-for="@Model.ImagePath" class="form-label mt-4">Image</label>
                <input type="file" asp-for="@Model.ImagePath" class="form-control">
            </div>
            <div></div>
            <div class="row">
                <div class="col-md-6">
                    <fieldset>
                        <div class="form-group mt-4">
                            <label asp-for="@Model.Event.Category" class="control-label"></label>
                            <select asp-for="@Model.Event.Category" class="form-control" asp-items="@Model.Categories"></select>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-6">
                    <fieldset>
                        <legend class="mt-4">Transports</legend>
                        @for (int i = 0; i < Model.Transports.Count(); i++)
                        {
                            <div class="form-check">
                                <input type="hidden" asp-for="@Model.Transports[i].Text " />
                                <input asp-for="@Model.Transports[i].Value" type="checkbox" class="form-check-input" />
                                <label asp-for="@Model.Transports[i].Value" class="form-check-label">
                                    @(Model.Transports[i].Text[..1].ToUpper() + @Model.Transports[i].Text[1..])
                                </label>
                            </div>
                        }
                    </fieldset>
                </div>
            </div>
            <div>
                <label for="ticketTpyeCount" class="form-label mt-4">Number of Ticket type</label>
                <select class="form-select w-auto" id="ticketTpyeCount">
                    <option value="0" selected>Free</option>
                    @for (int i = 1; i <= 10; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
                <div id="ticketTypesContainer"></div>
            </div>
            <div class="mt-4 text-end">
                <button class="btn btn-outline-success">Create Event</button>
            </div>
        </fieldset>
    </form>
</div>


<script>
    // Map
    const _lat = document.getElementById("latitude");
    const _long = document.getElementById("longitude");
    const initialMap = [13.736717, 100.523186];

    let map = L.map('map').setView(initialMap, 6);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    let marker = L.marker(initialMap).addTo(map);

    function onMapClick(e) {
        if (marker) {
            map.removeLayer(marker);
        }
        marker = L.marker(e.latlng).addTo(map);

        const latitude = e.latlng.lat;
        const longitude = e.latlng.lng

        _lat.value = latitude;
        _long.value = longitude;
        getCountryAndCity(latitude, longitude);
    }
    map.on('click', onMapClick);

    // Get Country and City
    const _countryName = document.getElementById("countryName");
    const _addressName = document.getElementById("addressName");
    function getCountryAndCity(lat, lng) {
        var url = `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&zoom=10&addressdetails=1`;

        fetch(url)
            .then((res) => res.json())
            .then((data) => {
                _countryName.value = data.address.country;

                const boundaryAddress = ["quarter", "suburb", "city", "postcode", "town", "state", "municipality", "county"];
                const address = []
                Object.entries(data.address).forEach(([key, value]) => {
                    if (value !== undefined && boundaryAddress.includes(key))
                        address.push(value)
                    console.log(`${key}, ${value}`)
                })

                _addressName.value = address.join(", ");
            })
            .catch(err => {
                console.log(err);
            })
    }

    //Add number of tickettype
    document.getElementById("ticketTpyeCount").addEventListener("change", function () {
        const ticketTypeCount = parseInt(this.value);
        const ticketTypeContainer = document.getElementById("ticketTypesContainer");
        ticketTypeContainer.innerHTML = "";

        for (let i = 0; i < ticketTypeCount; i++) {
            const ticketType = document.createElement("div");
            ticketType.className = "row"

            ticketType.innerHTML = `
            <div class="col-12">
                <hr />
                <span class="text-secondary">Ticket type No.${i + 1}</span>
            </div>
            <div class="col-md-6">
                <label class="form-label mt-4">Ticket type</label>
                <span class="text-secondary">#${i + 1}</span>
                <input type="text" class="form-control" id="ticketTypeName_${i}" placeholder="name">
            </div>
            <div class="col-md-6">
                <label class="form-label mt-4">Detail</label>
                <span class="text-secondary">#${i + 1}</span>
                <input type="text" class="form-control" id="ticketTypeDetail_${i}" placeholder="detail">
            </div>
            <div class="col-md-6">
                <label class="form-label mt-4">Price</label>
                <span class="text-secondary">#${i + 1}</span>
                <input type="number" class="form-control" id="ticketTypePrice_${i}" placeholder="price">
            </div>
            <div class="col-md-6">
                <label class="form-label mt-4">Max Capital</label>
                <span class="text-secondary">#${i + 1}</span>
                <input type="number" class="form-control" id="ticketTypeMaxCapital_${i}" placeholder="max capital">
            </div>
            `;
            ticketTypeContainer.appendChild(ticketType);

            // Update hidden inputs based on the visible input values
            document.getElementById(`ticketTypeName_${i}`).addEventListener("input", function () {
                document.getElementById(`templateName_${i}`).value = this.value;
            });
            document.getElementById(`ticketTypeDetail_${i}`).addEventListener("input", function () {
                document.getElementById(`templateDetail_${i}`).value = this.value;
            });
            document.getElementById(`ticketTypePrice_${i}`).addEventListener("input", function () {
                document.getElementById(`templatePrice_${i}`).value = this.value;
            });
            document.getElementById(`ticketTypeMaxCapital_${i}`).addEventListener("input", function () {
                document.getElementById(`templateMaxCapital_${i}`).value = this.value;
            });
        }
    });
    // Trigger change event on page load to initialize the form
    document.getElementById("ticketTpyeCount").dispatchEvent(new Event("change"));
</script>

EventManagementSystem/Areas/Admin/Views/EventsManager/Delete.cshtml
@model Event
<div class="container bg-dark py-5 px-5">
    <partial name="_AlertErrorSuccess" />
    <div asp-validation-for="All" class="text-danger px-md-5"></div>
    <fieldset class="px-lg-5">
        <legend class="text-center h1 fw-bold">DELETE EVENT</legend>
        <div class="row">
            <div class="col-md-6">
                <div>
                    <label asp-for="@Model.Title" class="form-label mt-4">Title</label>
                    <input readonly asp-for="@Model.Title" type="text" class="form-control" placeholder="required*">
                    <span asp-validation-for="@Model.Title" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    <label asp-for="@Model.ShortDescription" class="form-label mt-4">Short Description</label>
                    <textarea readonly asp-for="@Model.ShortDescription" class="form-control" rows="1" placeholder="Maximum 50 words"></textarea>
                </div>
            </div>
        </div>
        <div>
            <label asp-for="@Model.Description" class="form-label mt-4">Full Description</label>
            <textarea readonly asp-for="@Model.Description" class="form-control" rows="3" placeholder="Maximum 1000 words"></textarea>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="@Model.StartDate" class="form-label mt-4">Start Event Date</label>
                <input readonly asp-for="@Model.StartDate" class="form-control" type="date" />
            </div>
            <div class="col-md-4">
                <label asp-for="@Model.EndDate" class="form-label mt-4">End Event Date</label>
                <input readonly asp-for="@Model.EndDate" class="form-control" type="date" />
            </div>
            <div class="col-md-4">
                <label asp-for="@Model.VenueName" class="form-label mt-4">Venue Name</label>
                <input readonly asp-for="@Model.VenueName" type="text" class="form-control" placeholder="Venue Name">
            </div>
        </div>

        <div class="row mt-4 d-flex justify-content-center">
            <div class="col-md-6 mt-2">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">Latitude</span>
                    <input asp-for="@Model.Latitude" id="latitude" type="text" class="form-control w-25 bg-secondary-subtle" aria-label="latitude input" readonly>
                </div>
            </div>
            <div class="col-md-6 mt-2">
                <div class="input-group input-group-sm">
                    <span class="input-group-text">Longitude</span>
                    <input asp-for="@Model.Longitude" id="longitude" type="text" class="form-control w-25 bg-secondary-subtle" aria-label="longitude input" readonly>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label asp-for="@Model.Country" class="form-label mt-4">Country</label>
                <input readonly asp-for="@Model.Country" id="countryName" type="text" class="form-control" placeholder="required">
            </div>
            <div class="col-md-8">
                <label asp-for="@Model.Address" class="form-label mt-4">Address</label>
                <input readonly asp-for="@Model.Address" id="addressName" type="text" class="form-control" placeholder="required">
            </div>
        </div>
        <div>
            <label class="form-label mt-4">Image</label>
            <input type="text" value="@Model.Image" class="form-control" disabled>
        </div>
        <div></div>
        <div class="row">
            <div class="col-md-6">
                <fieldset>
                    <div class="form-group mt-4">
                        <label asp-for="@Model.Category" class="control-label"></label>
                        <select asp-for="@Model.Category" class="form-control disabled" disabled>
                            <option selected>@Model.Category.ToString()</option>
                        </select>
                    </div>
                </fieldset>
            </div>
            <div class="col-md-6">
                <fieldset>
                    <legend class="mt-4">Transports</legend>
                    @for (int i = 0; i < Model.Transports.Count(); i++)
                    {
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" checked disabled />
                            <label class="form-check-label">
                                @(Model.Transports[i].ToString()[..1].ToUpper() + @Model.Transports[i].ToString()[1..])
                            </label>
                        </div>
                    }
                </fieldset>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-sm-6 text-center d-flex align-items-sm-center align-items-md-start justify-content-center justify-content-md-start">
                    <div>
                        <label for="ticketTpyeCount" class="form-label mt-4">Number of Ticket type</label>
                        <select class="form-select w-auto" id="ticketTpyeCount">
                            <option value="0" selected>@Model.TicketTypes.Count</option>
                        </select>
                    </div>
                </div>
                @if (Model.TicketTypes.Count > 0)
                {
                    <div class="col-sm-6">
                        <form asp-controller="EventsManager" asp-action="DeleteTicketType" method="post" enctype="multipart/form-data">
                            @foreach (var ticketType in Model.TicketTypes)
                            {
                                <input name="ticketTypeIds" value="@ticketType.Id" enctype="multipart/form-data" hidden/>
                            }
                            <div class="text-sm-end text-center pt-sm-5 pt-3">
                                <button type="submit" class="btn btn-danger">Delete all ticket type</button>
                            </div>
                        </form>
                    </div>
                }
                <div id="ticketTypesContainer" class="row">
                    @{
                        var tickettypes = Model.TicketTypes.ToList();
                    }

                    @for (int i = 0; i < tickettypes.Count; i++)
                    {
                        <div class="col-12">
                            <hr />
                            <span class="text-secondary">Ticket type No.@(i + 1)</span>
                            <form asp-controller="EventsManager" asp-action="DeleteTicketType" method="post">
                                <div class="text-sm-end text-center">
                                    <input name="ticketTypeIds" value="@tickettypes[i].Id" hidden />
                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label mt-4">Ticket type @tickettypes[i].Id</label>
                            <span class="text-secondary">#@(i + 1)</span>
                            <input value="@tickettypes[i].Name" type="text" class="form-control" readonly>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label mt-4">Detail</label>
                            <span class="text-secondary">#@(i + 1)</span>
                            <input value="@tickettypes[i].Detail" type="text" class="form-control" readonly>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label mt-4">Price</label>
                            <span class="text-secondary">#@(i + 1)</span>
                            <input value="@tickettypes[i].Price" type="number" class="form-control" readonly>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label mt-4">Max Capital</label>
                            <span class="text-secondary">#@(i + 1)</span>
                            <input value="@tickettypes[i].MaxCapital" type="number" class="form-control" readonly>
                        </div>
                    }
                </div>
            </div>
        </div>
        <form asp-controller="EventsManager" asp-action="Delete" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="mt-4 text-end">
                <button type="submit" class="btn btn-danger">Delete Event</button>
            </div>
        </form>
    </fieldset>
</div>